### PR TITLE
Final code changes for the socranop-0.5 release (hopefully)

### LINKED ISSUE #17: installtool: Verify the new-content/old-content comparison has the desired result
Verify the new-content/old-content comparison has the desired result.

For now, this means the post-install and pre-uninstall cases.

We leave it to our users to decide about whether to run the pre-uninstall sudo script for the old version or not when doing updates from one version of scoranop to another.

### LINKED ISSUE #65: installtool: Help package builder remove installtool related files
When creating an OS package (rpm, deb, AUR, etc.), copying and remove files is done by the OS package manager (rpm/dnf, dpkg/apt, etc). `socranop-installtool` only helps at package build time, by creating and writing files to the package chroot.

So `socranop-installtool` is not needed after package build time, and the OS package does not need to ship `socranop-installtool` or its data files at all.

`socranop-installtool` should help the OS package remove itself (and the `data/` source files) from the package chroot.

See also https://github.com/socratools/socranop/issues/63

### LINKED ISSUE #66: installtool: clarify roles, then name, implement and document properly
As we discovered in https://github.com/socratools/socranop/issues/63, the socranop installtool `socranop-installtool` plays different roles, and the naming of these roles and therefore the actual roles are confusing. We should name things better, and fix the issues caused by the unclear roles. 

  * Run after `pip install socranop` to complete the installation (`socranop-installtool --post-install`)
      * copies a number of files to well known locations (e.g. icon files)
      * creates and writes a number of files adapted for its `socranop` installation to well known locations (e.g. D-Bus service file, desktop file for the GUI, udev rules file)
      * "if necessary", move privileged writing of files to a shell script to be run with `sudo` after inspection of the script by the user
      * "if necessary", run commands telling the system about the files it has just written (at this time, only one `udevadm trigger` command for each of the three supported USB devices)
    Incidentally, the command running part only happens in the sudo script which the `socranop-installtool --post-install` run generates, and therefore can only be executed after `socranop-installtool` has finished.

    A more accurate name for this would be `--post-pip-install`.

  * Run before `pip uninstall socranop` to prepare the uninstall (`socranop-installtool --pre-uninstall`)
      * remove a number of files from well known locations (e.g. icon files)
      * remove a number of files from well known locations (e.g. D-Bus service file, desktop file for the GUI, udev rules file)
      * "if necessary", move privileged removing of files to a shell script to be run with `sudo` after inspection of the script by the user
      * "if necessary", run commands telling the system about the files it has just removed (TODO `udevadm trigger` commands for each of the three supported USB devcies)
    Incidentally, the command running part only happens in the sudo script which the `socranop-installtool --pre-install` run generates, and therefore can only be executed after `socranop-installtool` has finished, i.e. after the files have actually been removed.

    A more accurate name for this would be `--pre-pip-uninstall`.

  * Run while building an OS binary package like `*.rpm`, `*.deb`, an AUR package, etc.
    Confusingly, this is also called `socranop-installtool --post-install` at this time, but with `--chroot CHROOT` attached.

      * copies a number of files to well known locations (e.g. icon files)
      * creates and writes a number of files adapted for its `socranop` installation to well known locations (e.g. D-Bus service file, desktop file for the GUI, udev rules file)
      * as all writing happens into a chroot buildroot, we expect to have the necessary privilege to write to that buildroot
      * TODO: Unclear what to do about the `udevadm trigger` commands. Perhaps write them to a script which the package can then ship or copy and run post package install, post package uninstall, and post package update (in case the udev rules file has changed from the old to the new package)?

    A more accurate name for this could be... `--package-build-install`, or... `--FIXME`?

Probably more aspects to follow.

### PR DESCRIPTION
**Pull request by ndim**
If all goes well, these are my final changes proposed for `socranop-0.5`.

I still have a few documentation parts to review and submit changes for. If I do not find any issues in those which suggest or require code changes, this PR will be my remaining code changes for socranop-0.5.

The main change is switching `socranop-installtool` from a mess of `--post-install` and `--pre-uninstall` with many combinations of options to three subcommands `post-pip-install`, `pre-pip-uninstall`, and `package-build-install` with much fewer combinations of options.

To increase the chance of package building working out of the box for many distributions, this could benefit from testing building packages which make use of `socranop-installtool package-build-install`.

### CODE REVIEW

**Comment by ndim** [comment]
I have been installing a number of VMs, and trying this with different operating systems and Python versions (Debian 11 Bullseye oldstable with Python 3.9, Debian 13 Trixie testing with Python 3.11, working on more like Arch and NixOS, but those are more work for me to install).

Unfortunately, I have been running into some weird things which need a closer look. The first thing is that the `pipenv install --dev` step fails on Debian 11. Working on that.

**Comment by ndim** [comment]
> Unfortunately, I have been running into some weird things which need a closer look. The first thing is that the `pipenv install --dev` step fails on Debian 11. I am working on that.

That one appears to have a simple fix: `pip install -U pipenv`.

The pipenv version Debian 11 ships is 11.9.0 (released 2018-03-21) which is too old. `pipenv install -U pipenv` upgrades to 2023.10.24 which is new enough.

I do not know which version of `pipenv` specifically starts working for `socranop`, but suffice to say pipenv switched to a YYYY.M.D type of version number with release 2018.5.18.

On to the next issue...

**Comment by ndim** [comment]
Fixed the Debian 11 issues.

**Review by lack — APPROVED** [review]
Solid as usual!

I'm fine merging this if you think it's seen enough testing...

**Comment by ndim** [comment]
This should be mostly fine now. If there is anything amiss, we can fix that later.

**Pull request merged**
