### PR TITLE
Add --wait option to socranop-ctl

### PR DESCRIPTION
**Pull request by lack**
The default behavior is now to exit (with error code) if no device
exists.

### CODE REVIEW

**Comment by ndim** [comment]
Uhm... is that now the same behaviour with or without `--no-dbus`?

**Comment by lack** [comment]
No, it only waits in dbus mode... Do you think that's important?

**Review by ndim — CHANGES_REQUESTED** [review]
Without a device attached, I have tested four cases:

```
[user@host socranop]$ $ socranop-ctl --no-dbus --set 3
No compatible device detected
[user@host socranop]$ 
```

As expected.

```
[user@host socranop]$ socranop-ctl --set 3
No compatible device detected
[user@host socranop]$ killall socranop-session-service
[user@host socranop]$ 
```

As expected.

```
[user@host socranop]$$ socranop-ctl --no-dbus --wait --set 3
No compatible device detected
[user@host socranop]$ 
```

The `--wait` argument appears to have no function at all in conjunction with `--no-dbus`.

```
[user@host socranop]$$ socranop-ctl --wait --set 3
No devices found... waiting for one to appear
New io.github.socratools.socranop connected
^CNo compatible device detected
[user@host socranop]$ killall socranop-session-service
[user@host socranop]$ 
```

And when going through the D-Bus service, `--wait` just waits for eternity, whether I plug in the Notepad-12FX or not.

This is not the behaviour I was led to expect from `--wait`.

*With* a device attached, `socranop-ctl` just sets, prints the audio routing, and exits, as expected.

**Comment by ndim** [comment]
> No, it only waits in dbus mode... Do you think that's important?

Neither the `socranop-ctl --help` output nor the man page qualify the description of `--wait` with "only works without --no-dbus given".

**Comment by ndim** [comment]
Personally, I find it surprising that the CLI supports waiting for a device to be connected. My standard expectation would be "no device connected? tell me, and exit.".

Command line programs are usually of the type which is launched, does its task, and then exits.

Waiting for a device to be connected I would only expect from a GUI, because GUI programs are designed to keep running eternally, and thus need to react to events happening during that eternity.

**Comment by ndim** [comment]
```
[user@host socranop]$ socranop-session-service 
No recognised device was found
Waiting for one to arrive...
Traceback (most recent call last):
  File "/home/ndim/proj/socratools/socranop/socranop/dbus.py", line 196, in uevent
    idProduct = int(device.get_property("ID_PRODUCT_ID"), 16)
TypeError: int() can't convert non-string with explicit base
[user@host socranop]$ 
```

This happens upon plugging in the device.

**Comment by ndim** [comment]
More information with the new debug output from `socranop-session-service`:

```
Device added (idVendor='05fc', idProduct=None)
Traceback (most recent call last):
  File "/home/ndim/proj/socratools/socranop/socranop/dbus.py", line 201, in uevent
    idProduct = int(idPStr, 16)
TypeError: int() can't convert non-string with explicit base
```

Why does GUdev give us a device without an idProduct string?

**Comment by lack** [comment]
Weird - That "wait for the device" thing used to work.  Honestly, it's not important to the CLI, but I'd like to fix it.  Maybe to unblock 0.5 I'll just remove it for now, and add an issue to fix it.

**Comment by grawity** [comment]
Copying from IRC:

The explanation is that udev properties are _not_ the same thing as sysfs attributes, so "idFoo" in sysfs does not automatically correspond to "ID_FOO" in udev; all properties are generated internally by udev rules and helpers which mostly just happen to load data from /sys.

In this case the `usb_id` udev rule reads idVendor/idProduct from /sys [and generates](https://github.com/systemd/systemd/blob/main/src/udev/udev-builtin-usb_id.c#L432-L439) the `ID_VENDOR_ID` / **`ID_MODEL_ID`** device properties, and yes it has always been called "ID_MODEL" for as long as usb_id has existed.

GUdev does have an interface to directly access sysfs attributes, so an alternative to the above is `get_sysfs_attr("idProduct")`, although using properties is probably preferred.

**Review by ndim — APPROVED** [review]
* default mode now does not wait: very good
  * when --wait is given, it does wait: good
  * when --no-dbus --wait is given, it warns about that combo and does not wait: good
  * documentation reflects that

Looks good to me.

**Pull request merged**
